### PR TITLE
Create AnimalIdentification

### PR DESCRIPTION
**Pull request by acash1809**
This is a CNN based project which Identifies categories from 4 classes of animal.

### CODE REVIEW

**Comment by acash1809** [comment]
Please review my PR.

**Comment by Kunal-Garg-12** [comment]
@acash1809 Please add this to Machine Learning rather than Data Analysis. I will merge the PR once the change is made

**Comment by acash1809** [comment]
@Kunal-Garg-12 
image
ok adding this in ML.

**Comment by Kunal-Garg-12** [comment]
@acash1809 This was added to DataAnalysis/ so I wanted it to be in an appropriate directory

**Pull request closed without merging**
